---
openapi: 3.0.1
swagger: '2.0'
servers:
- url: http://pepperrodeov2.test/api/v1/
info:
  title: Pepper Rodeo API
  version: '0.1'
basePath:
  default: v2
paths:
  "/grocery-lists":
    get:
      tags:
      - grocery-lists
      responses:
        '200':
          description: All grocery lists
    post:
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/GroceryList"
            required:
            - title
      tags:
      - grocery-lists
      responses:
        '201':
          description: A grocery list was created
  "/grocery-lists/{key}":
    get:
      parameters:
      - in: path
        name: key
        schema:
          type: integer
        required: true
        description: Numeric key of the grocery list to use
      tags:
      - grocery-lists
      responses:
        '200':
          description: A single grocery list
    delete:
      parameters:
      - in: path
        name: key
        schema:
          type: integer
        required: true
        description: Numeric key of the grocery list to use
      tags:
      - grocery-lists
      responses:
        '200':
          description: 'Grocery list with id: {id} has been deleted'
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GroceryList"
    patch:
      parameters:
      - in: path
        name: key
        schema:
          type: integer
        required: true
        description: Numeric key of the grocery list to use
      tags:
      - grocery-lists
      responses:
        '200':
          description: A single grocery list
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GroceryList"
      requestBody:
              content:
                application/json:
                  schema:
                    "$ref": "#/components/schemas/GroceryList"
                  required:
                  - title
  "/recipes":
    get:
      tags:
      - recipes
      responses:
        '200':
          description: All recipes
    post:
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Recipe"
            required:
            - title
      tags:
      - recipes
      responses:
        '201':
          description: A recipe was created
  "/recipes/{key}":
    get:
      parameters:
      - in: path
        name: key
        schema:
          type: integer
        required: true
        description: Numeric key of the grocery list to use
      tags:
      - recipes
      responses:
        '200':
          description: A single recipes
    patch:
      parameters:
      - in: path
        name: key
        schema:
          type: integer
        required: true
        description: Numeric key of the recipe to use
      tags:
      - recipes
      responses:
        '200':
          description: A single recipe
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Recipe"
      requestBody:
              content:
                application/json:
                  schema:
                    "$ref": "#/components/schemas/Recipe"
                  required:
                  - title
    delete:
      parameters:
      - in: path
        name: key
        schema:
          type: integer
        required: true
        description: Numeric key of the recipe to use
      tags:
      - recipes
      responses:
        '200':
          description: 'Recipe with id: {id} has been deleted'
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Recipe"
  "/grocerylist/{grocerylist-key}/add-recipe/{recipe-key}":
    post:
      parameters:
      - in: path
        name: grocerylist-key
        schema:
          type: integer
        required: true
        description: Numeric key of the grocery list to use
      - in: path
        name: recipe-key
        schema:
          type: integer
        required: true
        description: Numeric key of the recipe to use
      tags:
      - add-recipe-to-list
      responses:
        '200':
          description: A recipe was added to grocery list
  "/departments":
    get:
      tags:
      - departments
      responses:
        '200':
          description: All departments
components:
  securitySchemes:
    APIKey:
      type: apiKey
      in: query
      name: api_token
  schemas:
    GroceryList:
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        user_id:
          type: integer
    Recipe:
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        directions:
          type: string
        category_id:
          type: integer
        user_id:
          type: integer
security:
- APIKey: []
definitions: {}
